/*
 * This source file was generated by the Gradle 'init' task
 */
package com.wharvex.gos;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    // Close the root xml element of the log file when the app shuts down.
    Runtime.getRuntime().addShutdownHook(new Thread(new ShutdownRunnable()));

    // Start the kernel.
    var kernelProcess = new ProcessWrapper(ProcessType.KERNEL);
    kernelProcess.init();
    kernelProcess.start();
  }
}
