/*
 * This source file was generated by the Gradle 'init' task
 */
package com.wharvex.gos;

import com.wharvex.gos.utils.JFrameExt;
import com.wharvex.gos.utils.ShutdownRunnable;
import com.wharvex.gos.osland.ProcessType;
import com.wharvex.gos.osland.ProcessWrapper;

import javax.swing.*;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    // Close the root xml element of the log file when the app shuts down.
    Runtime.getRuntime().addShutdownHook(new Thread(new ShutdownRunnable()));

    SwingUtilities.invokeLater(() -> {
      JFrameExt.getInstance().setVisible(true);
    });

  }

  public static void loadKernel() {
    // Load the kernel.
    var kernelProcess = new ProcessWrapper(ProcessType.KERNEL);
    kernelProcess.init();
    kernelProcess.start();
  }

  public static void requestShutdown() {
    // Request shutdown.
    Runtime.getRuntime().exit(0);
  }
}
