/*
 * This source file was generated by the Gradle 'init' task
 */
package com.wharvex.gos.app;

import com.wharvex.gos.ui.JFrameExt;
import com.wharvex.gos.utils.ShutdownRunnable;

import javax.swing.*;

public class App {
  private static JFrameExt frame = JFrameExt.getInstance();
  private static ShutdownRunnable shutdownRunnable = new ShutdownRunnable();

  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    // Close the root xml element of the log file when the app shuts down.
    Runtime.getRuntime().addShutdownHook(new Thread(new ShutdownRunnable()));

    SwingUtilities.invokeLater(() -> {
      JFrameExt.getInstance().setVisible(true);
    });
  }
}
